use arrow_array::cast::AsArray;
use arrow_array::types::{
    Int8Type, Int16Type, Int32Type, Int64Type, UInt8Type, UInt16Type, UInt32Type, UInt64Type,
};
use arrow_array::{
    ArrayRef, Int8Array, Int16Array, Int32Array, Int64Array, UInt8Array, UInt16Array, UInt32Array,
    UInt64Array,
};
use arrow_schema::DataType;
use hashbrown::HashTable;
use std::sync::Arc;

use crate::core::CoreError;

/// Storage layer for a single native key type. `Interner` is a thin
/// wrapper that dispatches to this via the `Keys` enum.
///
/// Maps a slice of native `Copy` values to a dense, sequential `u32` id
/// space. Ids are assigned in first-seen order starting at `0`. The same
/// value always resolves to the same id.
///
/// Holds the index into `keys`, not the value itself, in `ids`, so each
/// value is stored once.
struct PrimitiveKeys<T> {
    ids: HashTable<u32>,
    keys: Vec<T>,
    hasher: ahash::RandomState,
}

/// Convert a `keys` length to the next `u32` id, or
/// [`CoreError::TooManyKeys`] if the id space is exhausted.
fn checked_next_id(len: usize) -> Result<u32, CoreError> {
    u32::try_from(len).map_err(|_| CoreError::TooManyKeys)
}

impl<T: Copy + Eq + std::hash::Hash> PrimitiveKeys<T> {
    fn new() -> Self {
        Self {
            ids: HashTable::new(),
            keys: Vec::new(),
            hasher: ahash::RandomState::new(),
        }
    }

    /// Resolve every value in `values` to its dense id, assigning new ids
    /// for values not yet seen. Interning an already-seen value never
    /// allocates, since `T` is `Copy` and we reuse the existing key.
    ///
    /// # Errors
    ///
    /// Returns [`CoreError::TooManyKeys`] if assigning a new id would
    /// exceed `u32::MAX` distinct keys.
    fn intern_slice(&mut self, values: &[T]) -> Result<Vec<u32>, CoreError> {
        // Built as a plain loop rather than `.map(...).collect()` so the hot
        // path only ever moves a bare `u32`, not a `Result<u32, CoreError>`
        // (much larger, since `CoreError` embeds `DataType`) on every value.
        let mut ids = Vec::with_capacity(values.len());
        for &value in values {
            let hash = self.hasher.hash_one(value);
            let id = if let Some(&id) = self.ids.find(hash, |&id| self.keys[id as usize] == value) {
                id
            } else {
                let id = checked_next_id(self.keys.len())?;
                self.keys.push(value);
                self.ids
                    .insert_unique(hash, id, |&id| self.hasher.hash_one(self.keys[id as usize]));
                id
            };
            ids.push(id);
        }
        Ok(ids)
    }
}

/// One variant per supported fixed-width integer type. Generated by the
/// `primitive_keys` macro so `PrimitiveKeys`'s intern/decode logic isn't
/// hand-duplicated per type.
macro_rules! primitive_keys {
    ($($variant:ident => ($arrow_ty:ty, $native:ty, $array_ty:ty)),+ $(,)?) => {
        enum Keys {
            $($variant(PrimitiveKeys<$native>)),+
        }

        impl Keys {
            /// Build the empty variant matching `data_type`, or `None` if
            /// `data_type` isn't a supported fixed-width integer type.
            fn for_data_type(data_type: &DataType) -> Option<Keys> {
                match data_type {
                    $(DataType::$variant => Some(Keys::$variant(PrimitiveKeys::new())),)+
                    _ => None,
                }
            }

            fn data_type(&self) -> DataType {
                match self {
                    $(Keys::$variant(_) => DataType::$variant,)+
                }
            }

            fn len(&self) -> usize {
                match self {
                    $(Keys::$variant(keys) => keys.keys.len(),)+
                }
            }

            fn intern(&mut self, array: &ArrayRef) -> Result<Vec<u32>, CoreError> {
                match self {
                    $(Keys::$variant(keys) => {
                        keys.intern_slice(array.as_primitive::<$arrow_ty>().values())
                    })+
                }
            }

            fn decode_ids_to_array(&self, ids: &[u32]) -> ArrayRef {
                match self {
                    $(Keys::$variant(keys) => {
                        let values: Vec<$native> =
                            ids.iter().map(|&id| keys.keys[id as usize]).collect();
                        Arc::new(<$array_ty>::from(values))
                    })+
                }
            }

            fn keys_array(&self) -> ArrayRef {
                match self {
                    $(Keys::$variant(keys) => Arc::new(<$array_ty>::from(keys.keys.clone())),)+
                }
            }
        }
    };
}

primitive_keys! {
    Int8 => (Int8Type, i8, Int8Array),
    Int16 => (Int16Type, i16, Int16Array),
    Int32 => (Int32Type, i32, Int32Array),
    Int64 => (Int64Type, i64, Int64Array),
    UInt8 => (UInt8Type, u8, UInt8Array),
    UInt16 => (UInt16Type, u16, UInt16Array),
    UInt32 => (UInt32Type, u32, UInt32Array),
    UInt64 => (UInt64Type, u64, UInt64Array),
}

/// Maps arbitrary fixed-width integer Arrow values to a dense, sequential
/// `u32` id space.
///
/// The `DataType` of the first array ever interned fixes the key type for
/// the interner's lifetime. Later calls with a different `DataType` are
/// rejected. Ids are assigned in first-seen order starting at `0`.
#[derive(Default)]
pub struct Interner {
    keys: Option<Keys>,
}

impl Interner {
    /// Create an empty interner.
    pub fn new() -> Self {
        Self::default()
    }

    /// The number of distinct keys interned so far.
    pub fn len(&self) -> usize {
        self.keys.as_ref().map_or(0, Keys::len)
    }

    /// Resolve every value in `array` to its dense id, assigning new ids
    /// for values not yet seen.
    ///
    /// The first call establishes the key `DataType`. Later calls with a
    /// different (but supported) `DataType` return
    /// [`CoreError::KeyTypeMismatch`]. A `DataType` outside the supported
    /// fixed-width integer set returns [`CoreError::UnsupportedType`].
    /// Assigning an id beyond `u32::MAX` distinct keys returns
    /// [`CoreError::TooManyKeys`].
    pub fn intern_array(&mut self, array: &ArrayRef) -> Result<Vec<u32>, CoreError> {
        if self.keys.is_none() {
            let keys = Keys::for_data_type(array.data_type())
                .ok_or_else(|| CoreError::UnsupportedType(array.data_type().clone()))?;
            self.keys = Some(keys);
        }
        let keys = self.keys.as_mut().unwrap();
        let expected = keys.data_type();
        if expected != *array.data_type() {
            return Err(CoreError::KeyTypeMismatch {
                expected,
                got: array.data_type().clone(),
            });
        }
        keys.intern(array)
    }

    /// Resolve dense ids back to an Arrow array of the established key type.
    ///
    /// # Panics
    ///
    /// Panics if any id was never assigned by [`Self::intern_array`].
    pub fn decode_ids_to_array(&self, ids: &[u32]) -> ArrayRef {
        match &self.keys {
            Some(keys) => keys.decode_ids_to_array(ids),
            None => empty_u32_array(),
        }
    }

    /// All interned keys, in first-seen (ascending id) order, as an Arrow
    /// array of the established key type.
    ///
    /// Returns an empty `UInt32` array if nothing has been interned yet.
    pub fn keys_array(&self) -> ArrayRef {
        match &self.keys {
            Some(keys) => keys.keys_array(),
            None => empty_u32_array(),
        }
    }
}

fn empty_u32_array() -> ArrayRef {
    Arc::new(UInt32Array::from(Vec::<u32>::new()))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    use arrow_array::StringArray;

    fn u32_array(values: Vec<u32>) -> ArrayRef {
        Arc::new(UInt32Array::from(values))
    }

    #[test]
    /// The same key always resolves to the same id.
    fn repeated_key_reuses_id() {
        let mut interner = Interner::new();
        let ids = interner.intern_array(&u32_array(vec![42, 42])).unwrap();
        assert_eq!(ids[0], ids[1]);
        assert_eq!(interner.len(), 1);
    }

    #[test]
    /// New keys are assigned sequential ids in first-seen order.
    fn new_keys_get_sequential_ids() {
        let mut interner = Interner::new();
        let ids = interner
            .intern_array(&u32_array(vec![100, 5, 100, 7]))
            .unwrap();
        assert_eq!(ids, vec![0, 1, 0, 2]);
        assert_eq!(interner.len(), 3);
    }

    #[test]
    /// decode_ids_to_array is the inverse of intern_array.
    fn decode_round_trips() {
        let mut interner = Interner::new();
        let ids = interner.intern_array(&u32_array(vec![1_000_000])).unwrap();
        let decoded = interner.decode_ids_to_array(&ids);
        assert_eq!(decoded.as_primitive::<UInt32Type>().value(0), 1_000_000);
    }

    #[test]
    /// Widely spaced keys are handled like any other key.
    fn sparse_keys() {
        let mut interner = Interner::new();
        let ids = interner
            .intern_array(&u32_array(vec![0, u32::MAX]))
            .unwrap();
        assert_ne!(ids[0], ids[1]);
        let decoded = interner.decode_ids_to_array(&ids);
        let decoded = decoded.as_primitive::<UInt32Type>();
        assert_eq!(decoded.value(0), 0);
        assert_eq!(decoded.value(1), u32::MAX);
    }

    #[test]
    /// keys_array() reflects first-seen order.
    fn keys_in_first_seen_order() {
        let mut interner = Interner::new();
        interner.intern_array(&u32_array(vec![9, 3, 9, 1])).unwrap();
        let keys = interner.keys_array();
        assert_eq!(keys.as_primitive::<UInt32Type>().values(), &[9, 3, 1]);
    }

    #[test]
    /// keys_array() on a virgin interner is an empty UInt32 array.
    fn keys_array_empty_when_virgin() {
        let interner = Interner::new();
        let keys = interner.keys_array();
        assert_eq!(keys.data_type(), &DataType::UInt32);
        assert_eq!(keys.len(), 0);
    }

    #[test]
    /// Other signed integer widths intern the same way as UInt32.
    fn signed_integer_types_are_supported() {
        let mut interner = Interner::new();
        let array: ArrayRef = Arc::new(Int64Array::from(vec![1_i64 << 40, 7]));
        let ids = interner.intern_array(&array).unwrap();
        assert_ne!(ids[0], ids[1]);
        let keys = interner.keys_array();
        assert_eq!(keys.as_primitive::<Int64Type>().values(), &[1 << 40, 7]);
    }

    #[test]
    /// Narrower unsigned integer widths intern the same way as UInt32.
    fn narrow_unsigned_types_are_supported() {
        let mut interner = Interner::new();
        let array: ArrayRef = Arc::new(arrow_array::UInt16Array::from(vec![1_u16, 2, 1]));
        let ids = interner.intern_array(&array).unwrap();
        assert_eq!(ids[0], ids[2]);
        assert_ne!(ids[0], ids[1]);
    }

    #[test]
    /// A different (but supported) key type on a later call is rejected.
    fn mismatched_type_errors() {
        let mut interner = Interner::new();
        interner.intern_array(&u32_array(vec![1, 2])).unwrap();
        let other: ArrayRef = Arc::new(Int64Array::from(vec![1_i64, 2]));
        let err = interner.intern_array(&other).unwrap_err();
        assert_eq!(
            err,
            CoreError::KeyTypeMismatch {
                expected: DataType::UInt32,
                got: DataType::Int64,
            }
        );
    }

    #[test]
    /// A type outside the fixed-width integer set is rejected.
    fn unsupported_type_errors() {
        let mut interner = Interner::new();
        let array: ArrayRef = Arc::new(StringArray::from(vec!["a", "b"]));
        let err = interner.intern_array(&array).unwrap_err();
        assert_eq!(err, CoreError::UnsupportedType(DataType::Utf8));
    }

    #[test]
    /// Assigning an id beyond u32::MAX errors instead of silently wrapping.
    fn too_many_keys_errors_instead_of_wrapping() {
        assert_eq!(checked_next_id(u32::MAX as usize), Ok(u32::MAX));
        assert_eq!(
            checked_next_id(u32::MAX as usize + 1),
            Err(CoreError::TooManyKeys)
        );
    }
}
